pipeline {
    agent any
    stages {
        stage('Prepare the environment') {
            steps {
                sh '. ./scripts/prepare_env.sh'
            }
        }
        stage('Test with coverage') {
            steps {
                sh './scripts/test_with_coverage.sh'
            }
        }
        stage('Uncovered Lines Bot') {
            steps {
                sh 'python3 -m gerrit_coverage $GIT_URL'
            }
        }
    }
}
