pipeline {
    agent any
    stages {
        stage('Prepare the environment') {
            steps {
                sh '. ./scripts/prepare_env.sh'
            }
        }
        stage('Test with coverage') {
            steps {
                sh './scripts/test_with_coverage.sh'
            }
        }
        stage('Uncovered Lines Bot') {
            steps {
                sh './env/bin/python3 -m report_not_covered_lines $GIT_URL'
            }
        }
        stage('Checking Style') {
            steps {
                sh './env/bin/python3 -m review_style_gerrit $GIT_URL'
            }
        }
    }
}


